[[advanced]]
  name = "Overview"
  weight = 10
  identifier = "overview"
  url = "/advanced/overview/"

[[advanced]]
  name = "Specifications"
  weight = 20
  identifier = "specifications"
  url = "/advanced/specifications/"

[[advanced]]
  name = "Safety First"
  weight = 30
  identifier = "safety"
  url = "/safety/correct-use/"

[[advanced]]
  name = "Reachy's software"
  weight = 40
  identifier = "software"
  url = "/advanced/software/"

[[advanced]]
  name = "Services"
  weight = 50
  identifier = "services"
  url = "/advanced/services/"

[[docs]]
  name = "What needs to be installed"
  weight = 20
  identifier = "installation"
  url = "/docs/installation/"

[[docs]]
  name = "Getting started"
  weight = 10
  identifier = "getting-started"
  url = "/docs/getting-started/"

# [[docs]]
#  name = "Using VR teleoperation"
#  weight = 50
#  identifier = "teleoperation"
#  url = "/docs/teleoperation/"

[[docs]]
  name = "Update Reachy"
  weight = 30
  identifier = "update"
  url = "/docs/update/"

[[docs]]
  name = "I have a problem!"
  weight = 40
  identifier = "debug"
  url = "/docs/debug/"

[[sdk]]
  name = "Getting Started"
  weight = 10
  identifier = "getting-started"
  url = "/SDK/getting-started/"

[[sdk]]
  name = "First moves"
  weight = 20
  identifier = "first-moves"
  url = "/SDK/first-moves/"

[[sdk]]
  name = "Mobile base"
  weight = 30
  identifier = "mobile-base"
  url = "/SDK/mobile-base/"

[[sdk]]
  name = "Application"
  weight = 40
  identifier = "application"
  url = "/SDK/application/"

[[vr]]
  name = "Introduction"
  weight = 10
  identifier = "introduction"
  url = "/VR/introduction/"

[[vr]]
  name = "Compatibility"
  weight = 20
  identifier = "compatibility"
  url = "/VR/compatibility/"

[[vr]]
  name = "VR Installation"
  weight = 30
  identifier = "installation"
  url = "/VR/installation/"

[[vr]]
  name = "Using the app"
  weight = 40
  identifier = "use-teleop"
  url = "/VR/use-teleop/"

[[dashboard]]
  name = "Introduction"
  weight = 10
  identifier = "introduction"
  url = "/dashboard/introduction"

[[dashboard]]
  name = "Content"
  weight = 20
  identifier = "content"
  url = "/dashboard/content"

[[dashboard]]
  name = "Installation"
  weight = 30
  identifier = "installation"
  url = "/dashboard/installation"

[[help]]
  name = "Help"
  weight = 10
  identifier = "help"
  url = "/help/check-dashboard/"

[[help]]
  name = "System"
  weight = 20
  identifier = "system"
  url = "/help/system/"

[[main]]
  name = "Description"
  weight = 10
  url = "/advanced/overview/full-kit"

[[main]]
  name = "Setup Reachy"
  url = "/docs/installation/full-installation-process/"
  weight = 20

# [[main]]
#   name = "Blog"
#   url = "/blog/"
#   weight = 90

[[main]]
  name = "Python SDK"
  weight = 30
  url = "/SDK/getting-started/introduction/"

[[main]]
  name = "VR"
  weight = 40
  url = "/VR/introduction/introduction"

[[main]]
  name = "Dashboard"
  weight = 50
  url = "/dashboard/introduction/introduction"

[[main]]
  name = "Help"
  weight = 60
  url = "/help/check-dashboard"

[[social]]
  name = "Twitter"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-twitter\"><path d=\"M23 3a10.9 10.9 0 0 1-3.14 1.53 4.48 4.48 0 0 0-7.86 3v1A10.66 10.66 0 0 1 3 4s-4 9 5 13a11.64 11.64 0 0 1-7 2c9 5 20 0 20-11.5a4.5 4.5 0 0 0-.08-.83A7.72 7.72 0 0 0 23 3z\"></path></svg>"
  url = "https://twitter.com/pollenrobotics"
  weight = 10

[[social]]
  name = "GitHub"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-github\"><path d=\"M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22\"></path></svg>"
  url = "https://github.com/pollen-robotics/"
  post = "v0.1.0"
  weight = 20

[[social]]
  name = "Discord"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 128 128\" fill=\"#000000\" stroke=\"currentColor\" stroke-width=\"5\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-discord\"><path d=\"M45.23 57.2c-6.16 0-11.17 5.6-11.17 12.48s5 12.47 11.17 12.47 11.16-5.59 11.16-12.47S51.38 57.2 45.23 57.2Zm0 21c-4 0-7.17-3.8-7.17-8.47s3.21-8.48 7.17-8.48 7.16 3.8 7.16 8.48S49.18 78.15 45.23 78.15Z\"/><path d=\"M121.83 59.58a156.78 156.78 0 0 0-11.52-31 2.1 2.1 0 0 0-.71-.77 87.08 87.08 0 0 0-15.23-7.17C84.55 17.07 79.91 17 79.72 17a2 2 0 0 0-2 1.72l-.6 4.17a133.14 133.14 0 0 0-26.28 0l-.6-4.17a2 2 0 0 0-2-1.72c-.19 0-4.83 0-14.65 3.61A87.08 87.08 0 0 0 18.4 27.81a2.1 2.1 0 0 0-.71.77 156.72 156.72 0 0 0-11.52 31C1 80.46 0 90.91 0 91.34a2 2 0 0 0 .49 1.5 55.2 55.2 0 0 0 18.2 12.74A76.32 76.32 0 0 0 38.48 111a2 2 0 0 0 1.92-1l5.4-9.25A105.08 105.08 0 0 0 64 102.24a105.08 105.08 0 0 0 18.2-1.51L87.6 110a2 2 0 0 0 1.72 1h.2a76.32 76.32 0 0 0 19.78-5.38 55.2 55.2 0 0 0 18.2-12.74 2 2 0 0 0 .49-1.5C128 90.91 127.05 80.46 121.83 59.58Zm-14.06 42.31a76.76 76.76 0 0 1-17.39 4.92l-4.08-7c4.68-1.24 14.42-4.46 21.83-11.2a2 2 0 1 0-2.69-3c-9 8.23-22.46 10.84-22.6 10.87h-.06A96.59 96.59 0 0 1 64 98.24a96.59 96.59 0 0 1-18.78-1.7h-.06c-.14 0-13.55-2.64-22.6-10.87a2 2 0 1 0-2.69 3c7.41 6.74 17.15 10 21.83 11.2l-4.08 7a76.08 76.08 0 0 1-17.39-4.92A52.24 52.24 0 0 1 4.08 90.8c.33-2.91 1.68-13.07 6-30.24A156.25 156.25 0 0 1 21 30.92 88.17 88.17 0 0 1 35 24.4a61.35 61.35 0 0 1 11.58-3.19l.35 2.39c-4 1-13.85 3.86-21.65 9.53a2 2 0 1 0 2.36 3.23c8.82-6.41 21-9.06 21.86-9.25A118.4 118.4 0 0 1 64 26.27a117.64 117.64 0 0 1 14.51.84c.91.19 13 2.83 21.86 9.25a2 2 0 1 0 2.36-3.23c-7.8-5.67-17.61-8.52-21.65-9.53l.35-2.39A61.75 61.75 0 0 1 93 24.4a88.17 88.17 0 0 1 14 6.52A156.25 156.25 0 0 1 118 60.56c4.29 17.17 5.64 27.33 6 30.24A52.24 52.24 0 0 1 107.77 101.89Z\"/><path d=\"M82.77 57.2c-6.15 0-11.16 5.6-11.16 12.48s5 12.47 11.16 12.47 11.17-5.59 11.17-12.47S88.93 57.2 82.77 57.2Zm0 21c-4 0-7.16-3.8-7.16-8.47s3.21-8.48 7.16-8.48 7.17 3.8 7.17 8.48S86.73 78.15 82.77 78.15Z\"/></svg>"
  url = "https://discord.gg/vnYD6GAqJR"
  post = "v0.1.0"
  weight = 30

# [[footer]]
#   name = "Privacy"
#   url = "/privacy-policy/"
#   weight = 10
